FROM alpine:3.11

nim-gcc:
    RUN apk add --no-cache gcc musl-dev wget && \
        wget https://nim-lang.org/download/nim-1.4.2-linux_x64.tar.xz && \
        tar -xvf nim-1.4.2-linux_x64.tar.xz
    ENV PATH "${PATH}:/nim-1.4.2/bin"
    RUN nimble refresh
