FROM alpine:3.11

dev:
    FROM ../../envs+dev
    RUN mkdir -p /src/flecs
    RUN git clone https://github.com/SanderMertens/flecs /src/flecs
    RUN mkdir -p /src/flecs/build
    WORKDIR /src/flecs/build
    #ENV CC musl-gcc
    RUN cmake ..
    RUN make
    ENV CFLAGS "${CFLAGS} -I/src/flecs/include"
    ENV LDFLAGS "${LDFLAGS} -L/src/flecs/build"
