FROM alpine:3.11

dev:
    RUN apk add --no-cache git gcc musl-dev make cmake

orcania:
    FROM +dev
    RUN git clone https://github.com/babelouest/orcania.git && \
        cd orcania && \
        mkdir build && \
        cd build && \
        cmake -DBUILD_STATIC=on -DWITH_STRSTR=on .. && \
        make && \
        make install


yder:
    FROM +orcania
    RUN git clone https://github.com/babelouest/yder.git && \
        cd yder && \
        mkdir build && \
        cd build && \
        cmake -DWITH_JOURNALD=off -DBUILD_STATIC=on .. && \
        make && \
        make install

nim:
    RUN apk add --no-cache gcc musl-dev wget
    RUN wget https://nim-lang.org/download/nim-1.4.2.tar.xz && \
        tar -xvf nim-1.4.2.tar.xz
    ENV LDFLAGS="-static"
    RUN cd nim-1.4.2 && sh build.sh 
    SAVE ARTIFACT nim-1.4.2/bin/nim AS LOCAL nim
